name: deploy_frontend

on:
  push:
        branches: [ main ]
        paths: 
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login with azure
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az storage blob upload-batch --account-name azureresumecounter  -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/cli@v1
      with:
        azcliveversion: 2.30.0
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeajc" --name "azureresumeajc" --resource-group "azureresumecounter" --no wait

  # Azure logout
    - name: logout
      run: |
            az logout
