name: deploy_frontend

# Deploy when push made from frontend folder.
on:
    push:
        branches: [ main ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - run: echo ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          verbosity: debug

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureresumecounter --destination '$web' --source frontend --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeajc" --name "azureresumeajc" --resource-group "azureresumecounter" --no-wait
                   
  # Azure logout 
    - name: logout
      run: |
            az logout
